TxUtils: Replacement for TransactionRunner with methods:   runNeedsRetry()   runInTransaction()   runInTransactionOnCommit()   runOnCommit()  plus transaction utility methods like assertNoTransaction() moved from  EJBUtil and elsewhere.
RetryException: Checked exception indicating a need to retry the
 outer transaction.

TxCallable TxRunnable: Replacements for Callable and Runnable
 that throw RetryException and nothing else.
 
DataService: Add flush() method to flush the transaction-scoped
 EntityManager. Nothing much to do with the DataModel, but convenient
 here.
 
Mailer: Send emails on transaction commit to avoid duplicate mails
 on retry.
 
HttpMethodsServlet2: Add a marshaler for EmailResource

**/*.java: Adapt to the above